INFO (hyperopt.mongoexp): Error while unpickling. Try installing dill via "pip install dill" for enhanced pickling support.
INFO (hyperopt.mongoexp): job exception: 'module' object has no attribute 'do_run'
INFO (hyperopt.mongoexp): Error while unpickling. Try installing dill via "pip install dill" for enhanced pickling support.
INFO (hyperopt.mongoexp): job exception: 'module' object has no attribute 'do_run'
INFO (hyperopt.mongoexp): Error while unpickling. Try installing dill via "pip install dill" for enhanced pickling support.
INFO (hyperopt.mongoexp): job exception: 'module' object has no attribute 'do_run'
INFO (hyperopt.mongoexp): Error while unpickling. Try installing dill via "pip install dill" for enhanced pickling support.
INFO (hyperopt.mongoexp): job exception: 'module' object has no attribute 'do_run'
INFO (hyperopt.mongoexp): Error while unpickling. Try installing dill via "pip install dill" for enhanced pickling support.
INFO (hyperopt.mongoexp): job exception: 'module' object has no attribute 'do_run'
INFO (hyperopt.mongoexp): job exception: No module named data.load
INFO (hyperopt.mongoexp): job exception: No module named data.load
INFO (hyperopt.mongoexp): job exception: No module named data.load
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '../data/processed/x_manifest.pickle'
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '../data/processed/x_manifest.pickle'
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '../data/processed/x_manifest.pickle'
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '../data/processed/x_manifest.pickle'
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '/home/alex/research/malware/src/data/../data/processed/x_manifest.pickle'
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '/home/alex/research/malware/src/data/../data/processed/x_manifest.pickle'
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '/home/alex/research/malware/src/data/../data/processed/x_manifest.pickle'
INFO (hyperopt.mongoexp): job exception: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout/mul:0", shape=(?, 200), dtype=float32).
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout/mul:0", shape=(?, 200), dtype=float32).
INFO (hyperopt.mongoexp): job exception: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout/mul:0", shape=(?, 200), dtype=float32).
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout/mul:0", shape=(?, 200), dtype=float32).
INFO (hyperopt.mongoexp): job exception: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout/mul:0", shape=(?, 200), dtype=float32).
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout/mul:0", shape=(?, 200), dtype=float32).
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout/mul:0", shape=(?, 200), dtype=float32).
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout/mul:0", shape=(?, 200), dtype=float32).
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: list index out of range
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: list index out of range
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: list index out of range
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: list index out of range
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: float argument required, not dict
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): job exception: Unknown format code 'f' for object of type 'str'
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: OOM when allocating tensor with shape[545333,200]
	 [[Node: random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=933486452, _device="/job:localhost/replica:0/task:0/gpu:0"](random_uniform/shape)]]
Caused by op u'random_uniform/RandomUniform', defined at:
  File "/home/alex/dnn/bin/hyperopt-mongo-worker", line 8, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1300, in main_worker
    return main_worker_helper(options, args)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1247, in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1074, in run_one
    result = worker_fn(spec, ctrl)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/base.py", line 838, in evaluate
    rval = self.fn(pyll_rval)
  File "train_hyperopt.py", line 27, in do_run
    m = model()
  File "/home/alex/research/malware/src/model/model.py", line 76, in model
    hidden = Dense(200, activation='relu', W_constraint=W_constraint, W_regularizer=W_regularizer())(all_inputs)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 281, in random_uniform_variable
    low, high, dtype=tf_dtype, seed=seed)(shape)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 98, in _initializer
    return random_ops.random_uniform(shape, minval, maxval, dtype, seed=seed)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 249, in random_uniform
    seed2=seed2)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 218, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

INFO (hyperopt.mongoexp): job exception: OOM when allocating tensor with shape[545333,200]
	 [[Node: random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=905139331, _device="/job:localhost/replica:0/task:0/gpu:0"](random_uniform/shape)]]
Caused by op u'random_uniform/RandomUniform', defined at:
  File "/home/alex/dnn/bin/hyperopt-mongo-worker", line 8, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1300, in main_worker
    return main_worker_helper(options, args)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1247, in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1074, in run_one
    result = worker_fn(spec, ctrl)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/base.py", line 838, in evaluate
    rval = self.fn(pyll_rval)
  File "train_hyperopt.py", line 27, in do_run
    m = model()
  File "/home/alex/research/malware/src/model/model.py", line 76, in model
    hidden = Dense(200, activation='relu', W_constraint=W_constraint, W_regularizer=W_regularizer())(all_inputs)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 281, in random_uniform_variable
    low, high, dtype=tf_dtype, seed=seed)(shape)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 98, in _initializer
    return random_ops.random_uniform(shape, minval, maxval, dtype, seed=seed)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 249, in random_uniform
    seed2=seed2)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 218, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

INFO (hyperopt.mongoexp): job exception: OOM when allocating tensor with shape[545333,200]
	 [[Node: random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=35668123, _device="/job:localhost/replica:0/task:0/gpu:0"](random_uniform/shape)]]
Caused by op u'random_uniform/RandomUniform', defined at:
  File "/home/alex/dnn/bin/hyperopt-mongo-worker", line 8, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1300, in main_worker
    return main_worker_helper(options, args)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1247, in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1074, in run_one
    result = worker_fn(spec, ctrl)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/base.py", line 838, in evaluate
    rval = self.fn(pyll_rval)
  File "train_hyperopt.py", line 27, in do_run
    m = model()
  File "/home/alex/research/malware/src/model/model.py", line 76, in model
    hidden = Dense(200, activation='relu', W_constraint=W_constraint, W_regularizer=W_regularizer())(all_inputs)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 281, in random_uniform_variable
    low, high, dtype=tf_dtype, seed=seed)(shape)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 98, in _initializer
    return random_ops.random_uniform(shape, minval, maxval, dtype, seed=seed)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 249, in random_uniform
    seed2=seed2)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 218, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: "'mwr'"
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): job exception: OOM when allocating tensor with shape[545333,200]
	 [[Node: random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=296038597, _device="/job:localhost/replica:0/task:0/gpu:0"](random_uniform/shape)]]
Caused by op u'random_uniform/RandomUniform', defined at:
  File "/home/alex/dnn/bin/hyperopt-mongo-worker", line 8, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1300, in main_worker
    return main_worker_helper(options, args)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1247, in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1074, in run_one
    result = worker_fn(spec, ctrl)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/base.py", line 838, in evaluate
    rval = self.fn(pyll_rval)
  File "train_hyperopt.py", line 15, in do_run
    m = model(l1=space['l1'], l2=space['l2'])
  File "/home/alex/research/malware/src/model/model.py", line 76, in model
    hidden = Dense(200, activation='relu', W_constraint=W_constraint, W_regularizer=W_regularizer())(all_inputs)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 281, in random_uniform_variable
    low, high, dtype=tf_dtype, seed=seed)(shape)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 98, in _initializer
    return random_ops.random_uniform(shape, minval, maxval, dtype, seed=seed)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 249, in random_uniform
    seed2=seed2)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 218, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: global name 'K' is not defined
INFO (hyperopt.mongoexp): job exception: global name 'K' is not defined
INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: Unable to create file (Unable to open file: name = '../models/regnoneg.l1-0.l2-0.1.mwr-0.4.weights.00-0.26.hdf5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): job exception: OOM when allocating tensor with shape[545333,200]
	 [[Node: random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=844101418, _device="/job:localhost/replica:0/task:0/gpu:0"](random_uniform/shape)]]
Caused by op u'random_uniform/RandomUniform', defined at:
  File "/home/alex/dnn/bin/hyperopt-mongo-worker", line 8, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1300, in main_worker
    return main_worker_helper(options, args)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1247, in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1074, in run_one
    result = worker_fn(spec, ctrl)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/base.py", line 838, in evaluate
    rval = self.fn(pyll_rval)
  File "train_hyperopt.py", line 18, in do_run
    m = model(l1=space['l1'], l2=space['l2'])
  File "/home/alex/research/malware/src/model/model.py", line 78, in model
    hidden = Dense(200, activation='relu', W_constraint=W_constraint, W_regularizer=W_regularizer())(all_inputs)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 281, in random_uniform_variable
    low, high, dtype=tf_dtype, seed=seed)(shape)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 98, in _initializer
    return random_ops.random_uniform(shape, minval, maxval, dtype, seed=seed)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 249, in random_uniform
    seed2=seed2)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 218, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: Unable to create file (Unable to open file: name = '/home/alex/dnn/bin../models/regnoneg.l1-0.l2-0.mwr-0.4.weights.00-0.99.hdf5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): job exception: Unable to create file (Unable to open file: name = '/home/alex/dnn/bin../models/regnoneg.l1-0.01.l2-0.0666666666667.mwr-0.4.weights.00-0.24.hdf5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): job exception: OOM when allocating tensor with shape[545333,200]
	 [[Node: random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=389590330, _device="/job:localhost/replica:0/task:0/gpu:0"](random_uniform/shape)]]
Caused by op u'random_uniform/RandomUniform', defined at:
  File "/home/alex/dnn/bin/hyperopt-mongo-worker", line 8, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1300, in main_worker
    return main_worker_helper(options, args)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1247, in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1074, in run_one
    result = worker_fn(spec, ctrl)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/base.py", line 838, in evaluate
    rval = self.fn(pyll_rval)
  File "train_hyperopt.py", line 18, in do_run
    m = model(l1=space['l1'], l2=space['l2'])
  File "/home/alex/research/malware/src/model/model.py", line 78, in model
    hidden = Dense(200, activation='relu', W_constraint=W_constraint, W_regularizer=W_regularizer())(all_inputs)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 281, in random_uniform_variable
    low, high, dtype=tf_dtype, seed=seed)(shape)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 98, in _initializer
    return random_ops.random_uniform(shape, minval, maxval, dtype, seed=seed)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 249, in random_uniform
    seed2=seed2)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 218, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

INFO (hyperopt.mongoexp): job exception: OOM when allocating tensor with shape[545333,200]
	 [[Node: random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=972064368, _device="/job:localhost/replica:0/task:0/gpu:0"](random_uniform/shape)]]
Caused by op u'random_uniform/RandomUniform', defined at:
  File "/home/alex/dnn/bin/hyperopt-mongo-worker", line 8, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1300, in main_worker
    return main_worker_helper(options, args)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1247, in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/mongoexp.py", line 1074, in run_one
    result = worker_fn(spec, ctrl)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/hyperopt/base.py", line 838, in evaluate
    rval = self.fn(pyll_rval)
  File "train_hyperopt.py", line 18, in do_run
    m = model(l1=space['l1'], l2=space['l2'])
  File "/home/alex/research/malware/src/model/model.py", line 78, in model
    hidden = Dense(200, activation='relu', W_constraint=W_constraint, W_regularizer=W_regularizer())(all_inputs)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 281, in random_uniform_variable
    low, high, dtype=tf_dtype, seed=seed)(shape)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/init_ops.py", line 98, in _initializer
    return random_ops.random_uniform(shape, minval, maxval, dtype, seed=seed)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/random_ops.py", line 249, in random_uniform
    seed2=seed2)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 218, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/alex/dnn/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

INFO (hyperopt.mongoexp): Caught signal 2, shutting down.
INFO (hyperopt.mongoexp): job exception: 2
INFO (hyperopt.mongoexp): job exception: Unable to create file (Unable to open file: name = '/home/alex/dnn/bin/../models/regnoneg.l1-0.0333333333333.l2-0.0666666666667.mwr-0.3.weights.00-0.21.hdf5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): job exception: global name 'as_dense' is not defined
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '../data/processed/x_manifest_mal.pickle'
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '../data/processed/x_manifest_mal.pickle'
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '../data/processed/x_manifest_mal.pickle'
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: '../data/processed/x_manifest_mal.pickle'
INFO (hyperopt.mongoexp): job exception: Unable to create file (Unable to open file: name = '/home/alex/research/malware/models/regnoneg10.l1-0.0666666666667.l2-0.1.mwr-0.3.weights.00-0.19.hdf5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): Error while unpickling. Try installing dill via "pip install dill" for enhanced pickling support.
INFO (hyperopt.mongoexp): job exception: 'module' object has no attribute 'do_run'
INFO (hyperopt.mongoexp): Error while unpickling. Try installing dill via "pip install dill" for enhanced pickling support.
INFO (hyperopt.mongoexp): job exception: 'module' object has no attribute 'do_run'
INFO (hyperopt.mongoexp): Error while unpickling. Try installing dill via "pip install dill" for enhanced pickling support.
INFO (hyperopt.mongoexp): job exception: 'module' object has no attribute 'do_run'
INFO (hyperopt.mongoexp): Error while unpickling. Try installing dill via "pip install dill" for enhanced pickling support.
INFO (hyperopt.mongoexp): job exception: 'module' object has no attribute 'do_run'
INFO (hyperopt.mongoexp): job exception: 'History' object has no attribute '__getitem__'
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): job exception: index out of bounds: 0 <= 550 <= 556, 0 <= 560 <= 556, 550 <= 560
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): job exception: index 5 is out of bounds for axis 0 with size 5
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): job exception: 'status'
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
INFO (hyperopt.mongoexp): Caught signal 15, shutting down.
